

mail:
    host: smtp.gmail.com
    port: 587
    username: shrikant.shinde@mitaoe.ac.in
    password:  bswl talt iwvq takd
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail.javamail: DEBUG
# service registers under this name
spring:
  application:
    name: EmailAuthentification

#discover ser
  config:
    import:
    - configserver:http://localhost:8088

    spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingsystem
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  main:
    web-application-type: reactive


    